### ISSUE TITLE
CLI invocation

### ISSUE THREAD

**Issue by basil** [neanes/neanes#1046]
I publish scores at https://byzantinemusic.org but it is a bit of a challenge to keep it up-to-date. It is already very out-of-date, as I have created new scores that haven't been published, and even the existing scores that are there were generated with an older version of Neanes without the features and bug fixes in newer versions.

Ideally, I would like to write a CI/CD setup for my web site where my source files are compiled into PDF files on every commit and uploaded to my web site. In order to do that, I need to be able to invoke it from the CLI to generate PDF files. Something like this:

```bash
$ find . -type f -name '*.byzx' -print0 | xargs -0 neanes
```

**Comment by danielgarthur** [comment]
Added in the latest release. You can use, for example, 

`$ find . -type f -name '*.byzx' -print0 | xargs -0 neanes --silent-pdf`

Note that if you are using this for CI, you will need to use a runner that can run Electron (probably needs X11 for a Linux runner).

**Comment by danielgarthur** [comment]
A working example of a Github workflow is [here](https://github.com/neanes/neanes/blob/b4735453f5bbf084546b751425a7527c2fef29b1/.github/workflows/rebuild-example-pdfs.yml). It uses xvfb for the display server.

This example does not include a possible necessary step for other scores: if you use fonts not included in Neanes, you will need to first download and install the fonts.
