### ISSUE TITLE
MacOS 10.15 Compatibility

### ISSUE THREAD

**Issue by isvarnas** [neanes/neanes#1091]
New Version is not compatible with macOS Catalina (Version 10.15.7). It requires MacOS 11.0 or higher.

**Comment by danielgarthur** [comment]
Apple has discontinued all support for Catalina and a lot of software will no longer receive updates for it. I don't like Apple's policy regarding backwards compatibility, but I think the only options would be to revert to an older version of Electron or maintain two builds. Neither option seems great.
