### ISSUE TITLE
Export to png

### ISSUE THREAD

**Issue by gugushvili** [neanes/neanes#1117]
This might a priori be a Mac issue and I'm not sure it's reproducible on other machines either: exporting to pdf and html works as expected, but export to png cuts off the right margin and as a result part of the music score is lost. I'm running Sequoia 15.1.1.

Anybody with similar experience?

**Comment by PsaltyDog** [comment]
For me the entire page is shifted to the right:

![Image](https://github.com/user-attachments/assets/8c4e0ae3-8f96-42ec-bed2-b0458229a36b)

It isn't consistent, though, some pages export fine. 

I'm running Sonoma 14.6.1 and Neanes 0.4.51

**Comment by gugushvili** [comment]
My Neanes version info is in the screenshot.

I seem to remember ( ? ) that with some older versions of both OS and Neanes, png export did work as expected (at least to the limited extent that I used it).

![Image](https://github.com/user-attachments/assets/6bd2f4bb-5c0f-4bbb-be08-404fb6b0c0f6)

**Comment by gugushvili** [comment]
I had a 3-page doc where all the pages got shifted. On the other hand, in a 2-page doc only the second page was incorrect.

**Comment by PsaltyDog** [comment]
It is exactly the same for me. I've done the following combinations: 

1-page doc: correct
2-page doc: first page correct, second page shifted
4-page doc: all pages shifted

**Comment by danielgarthur** [comment]
After a little bit of testing, I can consistently reproduce it by changing my window size. Strangely, the _narrower_ I make the window the _less_ it is cut off. If the window is wider, it starts to cut off more and more as I make it wider and wider. At full screen it has cut the most out. This is on Windows. Haven't tried Mac or Linux. 

The digging continues.

**Comment by PsaltyDog** [comment]
Yes, it's the same for me on Mac, but only by narrowing the window horizontally, not vertically.

**Comment by danielgarthur** [comment]
Fixed in the latest release.
