### ISSUE TITLE
Copy-Paste Option

### ISSUE THREAD

**Issue by EliasElward** [neanes/neanes#1118]
Hello,

I was wondering if it’s possible to copy and paste from one project to another?

**Comment by danielgarthur** [comment]
Yes. If you open both files, you can select neumes and text elements and so on from one file. Hold Shift while clicking to select multiple elements at the same time. Eg. click the first element, hold Shift and click the last element to highlight everything in between. Then copy (Ctrl+C). Then open the tab with the other file and paste. To paste with lyrics: Shift + Ctrl + V. To paste without lyrics: Ctrl + V.

**Comment by danielgarthur** [comment]
I'm closing this, but feel free to re-open if you still have a question.
