### ISSUE TITLE
Intercalated Syllables in Non-Greek Scripts

### ISSUE THREAD

**Issue by PeTH2** [neanes/neanes#1150]
This may have been covered before, but presently there is no way to disable the Auto Greek melisma feature. 

Under normal circumstances this is not an issue, however, when a thesis calls for a _χ_ instead of a gorthmikon or pelastikon, it sometimes deletes other melisma lines if a Greek _χ_ is added.

Presently in compositions and transcriptions, I have resorted to replacing `χ___` with `(h)___`, but this is not visually pleasing.

Would there be a way to disable Greek melismata, or at least include a variant _χ_ character in the toolbar (with the gorthmikon and pelastikon) to be used in combination with Latin letters?
 
![Image](https://github.com/user-attachments/assets/f2e9636b-6ef3-475e-bf8e-0bfdce36386f)
![Image](https://github.com/user-attachments/assets/533d012d-0471-4602-b16d-0849af60ef9c)

**Comment by danielgarthur** [comment]
Is _chi_ ever used by itself in Greek texts? The examples that I could find always include the vowel afterward (e.g. `χε`). If so, I'm thinking the check for "is this syllable Greek" should ignore the usual rules if no Greek vowel is present (or at least if _chi_ is present without a vowel).
