### ISSUE TITLE
Different behavior of kentimata in relation to the lyrics toolbar or direct input of lyrics in the music text ( for Greek texts )

### ISSUE THREAD

**Issue by Beatl3** [neanes/neanes#1166]
When having kentimata on their own and not in conjunction with other characters different handling is needed depending whether one inputs lyrics with the toolbar or directly. I suspect this has to do with the difference between Greek and English where English uses the dash for continuing vowels?

If I enter directly the vowel/syllable of the kentimata in the music text and then activate the lyrics toolbar, the lyrics get messed up. For the lyrics toolbar to work correctly I need to remove the syllable I entered in the music text. When I remove it, it will be filled in the music text and it will appear gray, but it prints correctly anyway.

**Comment by danielgarthur** [comment]
For Greek see this [brief explanation](https://neanes.github.io/neanes/guide/advanced.html#greek). 

For Greek, use the underscore (`_`) to indicate repeated syllables. The repeated syllables will appear as grey until you print/export, then they will be the normal text color. This is to indicate that they are melismatic syllables.

If I understood correctly, it sounds like you may have put a repeated vowel under the kentimata without using the underscore, which causes the lyrics manager to misinterpret the vowel as a non-melismatic vowel.

**Comment by Beatl3** [comment]
Thanks, now I know I need to use the underscore in the music text in such cases!
