### ISSUE TITLE
Playback speed is not granular enough

### ISSUE THREAD

**Issue by basil** [neanes/neanes#221]
A multiplier of 0.5x, 0.75, 1x, etc is fairly arbitrary. Would be nice to allow the user to simply enter beats per minute and play back the score at the desired tempo.

**Comment by danielgarthur** [comment]
The playback speed is intended to affect the speed of the entire score while still keeping the relative distances between tempos within the score. So if you have a score with multiple tempo changes, i.e. verses followed by slow stichera, mixed with faster heirmologic pieces, even 2x playback speed will keep the stichera slower than the heirmologic pieces. It's similar to the playback speed found in Finale or Musescore, except those applications have a fancier slider that slides between, say, 10% and 300%.

The intention is that it could be used to listen to a slow piece to check for mistakes, but at a faster tempo so you don't have to listen for so long.

**Comment by basil** [comment]
OK, the main thing I am complaining about is I can't get the tempo I want. It's always either too fast or too slow. A fancier slider would definitely solve that pain point.

**Comment by danielgarthur** [comment]
Musescore's play panel let's you slide the tempo % and it shows you the new BPM based on the currently selected note's original BPM. I'm all for adding that, the dropdown was more of a quick stop gap along the way.

**Comment by danielgarthur** [comment]
Added a speed slider to [0.4.20](https://github.com/neanes/neanes/releases/tag/v0.4.20).
