### ISSUE TITLE
Plagal of the 4 Mode

### ISSUE THREAD

**Issue by NickNestore** [neanes/neanes#514]
Hi, I can't find the signature of the plagal of the fourth mode  qPa
![pl4](https://github.com/neanes/neanes/assets/160590578/bb47d4b0-f77c-4ca4-a4da-36673c0f3de2)

**Comment by danielgarthur** [comment]
Added to version `0.4.12`. The auto-updater for version `0.4.11` may not function since the project was switched to the Neanes organization within Github. So you may need to download the new version from the [Releases](https://github.com/neanes/neanes/releases/latest) page.

Out of curiosity, the only place I've seen this mode is in the triple-meter polyeleos where it's used to ease the transition between the first mode and the plagal fourth mode. Is it used elsewhere?

**Comment by NickNestore** [comment]
I've recently started getting into psaltic music. I am adapting exactly this polieleos into Italian

> Il giorno 21 feb 2024, alle ore 19:11, danielgarthur ***@***.***> ha scritto:
> 
> Added to version 0.4.12. The auto-updater for version 0.4.11 may not function since the project was switched to the Neanes organization within Github. So you may need to download the new version from the Releases <https://github.com/neanes/neanes/releases/latest> page.
> 
> Out of curiosity, the only place I've seen this mode is in the triple-meter polyeleos where it's used to ease the transition between the first mode and the plagal fourth mode. Is it used elsewhere?
>

**Comment by NickNestore** [comment]
I downloaded the latest version, thanks. But the Zo sounds strange

> Il giorno 21 feb 2024, alle ore 19:11, danielgarthur ***@***.***> ha scritto:
> 
> Added to version 0.4.12. The auto-updater for version 0.4.11 may not function since the project was switched to the Neanes organization within Github. So you may need to download the new version from the Releases <https://github.com/neanes/neanes/releases/latest> page.
> 
> Out of curiosity, the only place I've seen this mode is in the triple-meter polyeleos where it's used to ease the transition between the first mode and the plagal fourth mode. Is it used elsewhere?
>

**Comment by danielgarthur** [comment]
Do you mean the zo is not a perfect fifth above pa? If so, please zip the byz or byzx file and attach it to a comment.

**Comment by NickNestore** [comment]
I tried, but the file is too bigInviato da iPhoneIl giorno 22 feb 2024, alle ore 04:32, danielgarthur ***@***.***> ha scritto:﻿
Do you mean the zo is not a perfect fifth above pa? If so, please zip the byz or byzx file and attach it to a comment.
