### ISSUE TITLE
[ENHANCEMENT] Add Plagal First Triphonic signature

### ISSUE THREAD

**Issue by neobabis** [neanes/neanes#516]
**One more signature for Plagal First mode**
Plagal First Triphonic
![martiria](https://github.com/neanes/neanes/assets/48261152/6c09dc6b-d392-4e32-9747-faf73fca5cc8)

**For example**
![egkomio](https://github.com/neanes/neanes/assets/48261152/4702f873-5404-4b91-8ae1-96451911a59d)

**Solution**
_ModeKey.ts_
`  {
    id: 505,
    mode: 5,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Thi,
    description: 'model:modeKey.triphonic',
    martyria: ModeSign.Alpha,
    note: ModeSign.Pa,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusKentimaAbove,
  },`

**Comment by danielgarthur** [comment]
Thanks! I've merged this in and it is available in [v0.4.13](https://github.com/neanes/neanes/releases/tag/v0.4.13).
