### ISSUE TITLE
[ENHANCEMENT] Default Styles for Text Box

### ISSUE THREAD

**Issue by neobabis** [neanes/neanes#525]
Under File > Page Setup
there is no option to set default style for the Text Box

The Text Box currently defaults to the 'Lyrics' style, but it's crucial to establish a different default style.

Additionally, it might be beneficial to adjust the line height.

**Comment by danielgarthur** [comment]
Added to[ 0.4.17](https://github.com/neanes/neanes/releases/tag/v0.4.17).

<img width="296" alt="image" src="https://github.com/neanes/neanes/assets/4132779/7b1077d8-bda4-446b-b9b4-19ce4349366f">
