### ISSUE TITLE
[BUG] Combining of neumes in RTL working in LTR fashion.

### ISSUE THREAD

**Issue by mattsmi** [neanes/neanes#554]
**This bug was found in 0.4.17 using Melkite RTL Page Set-up**

- [x] Desktop

**Describe the bug**
In order to have the combining characters Homalon and Heteron appear correct when applying them to neumes in a right-to-left page, one must select the latter neume not the first neume. This has the added deleterious effect that lines split between combined neumes, because the system appears to understand the combination as different, i.e. as if it were combing left to right. That is, in selecting the latter neume to make the Homalon or Heteron appear in the correct place on the page, one is actually combining the latter neume and the subsequent neume; the first neume is ignored in RTL.

This has a side-effect that prohibits changing the direction of the page. For all parts of a score written right to left, when the Page Set-up is changed back to left-to-right, all neumes appears correctly in the same order, including phthoræ and other incidentals. However, the combined characters appear correct in left-to-right order but are not reversed when the Page Set-up is changed to right-to-left.

**To Reproduce**
1. Attempt to combine two neumes in LTR mode and then reverse the Page Set-up direction.
2. Combine two neumes in RTL mode.
[inna yousuf.zip](https://github.com/neanes/neanes/files/14553810/inna.yousuf.zip)
[inna yousuf.zip](https://github.com/neanes/neanes/files/14553811/inna.yousuf.zip)

3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behaviour**
That combining neumes in RTL would behave as in LTR mode: i.e. select the first neume of the combination and then the combining character.

**Screenshots or files**
Attached a PDF (see the end of Line 5 for an example) and the Neanes file. There are also two examples on the final page.

**Desktop Version (please complete the following information, if applicable):**

- OS: Linux Mint 21.3.
- 0.4.17

**Comment by danielgarthur** [comment]
Fixed in [0.4.18](https://github.com/neanes/neanes/releases/tag/v0.4.18).
