### ISSUE TITLE
[BUG] Exporting a RTL score to HTML produced LTR output.

### ISSUE THREAD

**Issue by mattsmi** [neanes/neanes#581]
**This bug was found in**

- [x] Desktop

**Describe the bug**
I exported a RTL hymn to HTML and the result was LTR, and thus garbled.

**To Reproduce**
Just export to HTML

**Expected behaviour**
It should appear in RTL, if the original Neanes score is in RTL.

**Resolution**
Change the first line of the output HTML file to: <html dir="rtl"> . That will fix it.

**Comment by danielgarthur** [comment]
Added to [0.4.21](https://github.com/neanes/neanes/releases/tag/v0.4.21). There is at least one issue that I know of, that is also an issue for English LTR scores. If the screen size is adjusted such that a melisma is broken across a line, the melisma is not always rendered correctly.
