### ISSUE TITLE
Open Score dialog is not fully modal

### ISSUE THREAD

**Issue by basil** [neanes/neanes#591]
**This bug was found in**

- [x] Desktop
- [ ] Web App
- [ ] Both

**Describe the bug**
On Linux (but not Windows or macOS) the open dialog is not fully modal, as I can click into the application behind it and make it disappear (even though clicking into the application doesn't do anything).

**To Reproduce**

1. Open Neanes
2. Go to File, Open
3. You see an Open Score dialog box
4. Click on the Ison button in the neume toolbar

**Expected behavior**
No ison is inserted in the score, and the Open Score dialog stays present in the middle of the screen until you press either Open or Cancel. Note: This is the actual behavior on Windows and macOS. macOS is nice enough to gray out the application in the background to make it clear that clicking there won't do anything. Windows doesn't gray it out, but "yells" at you by flashing the border of the Open Score dialog if you try to click outside of it. The point is, in all cases the Open Score dialog stays present in the middle of the screen until you press either Open or Cancel.

**Actual behavior**
Only on Linux, clicking in the application while the Open Score dialog is open will hide the Open Score dialog in the background, although the application remains unresponsive (i.e., no ison is inserted into the score, as expected). The only way to get the application to become responsive again is to press Alt-Tab to make the Open Score dialog visible again in the foreground, and then press either Open or Cancel.

**Screenshots or files**
N/A

**Desktop Version (please complete the following information, if applicable):**

Neanes: Tip of trunk
OS: Ubuntu 22.04.4 LTS x86_64 
Kernel: 5.15.0-101-generic 
Desktop Environment: KDE Plasma
Window Manager: KWin
Theme: Breeze Dark [Plasma], Breeze [GTK2/3]
Icons: [Plasma], breeze-dark [GTK2/3]

**Additional context**
I know the problematic behavior is not intrinsic to Linux because my other KDE applications work as expected, as does Firefox. So this seems specific to Neanes and/or Electron. For example, my other KDE applications gray out the application when the Open dialog is open (like in macOS) and clicking into the grayed out area doesn't background the Open dialog.

This bug has slowly been driving me nuts as I always lose the open window and have to tab through lots of other windows to find it again.

**Comment by danielgarthur** [comment]
Could be related to https://github.com/electron/electron/issues/32857?

**Comment by basil** [comment]
That bug seems to be about a different problem; namely, different behavior opening a modal dialog the first vs second time when not passing a window object to `showOpenDialog` / `showSaveDialog`. That bug is reproducible in Fiddle, but it isn't the problem I'm having. And we are passing a window object to `showOpenDialog` / `showSaveDialog`. The problem I'm having is also reproducible in Fiddle, which is that once a modal dialog is open it is (erroneously) possible to hide it by clicking into the application.

**Comment by basil** [comment]
Fixed in https://github.com/electron/electron/pull/42045, which we appear to have adopted at some point through Dependabot updates. :tada:
