### ISSUE TITLE
Downward attraction in descending scale showing doubling of the attraction/flattening effect

### ISSUE THREAD

**Issue by mattsmi** [neanes/neanes#606]
**This bug was found in**

- [x] Desktop

**Describe the bug**
See attached exercise (Exercise 2.4 from Basilios Psilacos, *Byzantine Ecclesiastical Music*, 2nd ed.). After the Ni' (second martyria), there is an ison and then an apostrophos. The apostrophos flattens the Ke, but the next ison also seems to flatten the Ke. An ison should always be the same pitch as the previous note.

**Screenshots or files**
If applicable, add screenshots to help explain your problem. You may also upload a `byz` or `byzx` file, but you must first zip it and upload the `zip` file.

**Desktop Version (please complete the following information, if applicable):**

- OS: Linux Mint 21.3

[Ex2_4 Psilacos.zip](https://github.com/neanes/neanes/files/14901510/Ex2_4.Psilacos.zip)

**Comment by danielgarthur** [comment]
This is related to #213 and should probably be fixed at the same time.

**Comment by danielgarthur** [comment]
Fixed in [0.4.44](https://github.com/neanes/neanes/releases/tag/v0.4.44).
