### ISSUE TITLE
[BUG] Export/Print to PDF not functioning as intended

### ISSUE THREAD

**Issue by Cityyankee24** [neanes/neanes#634]
**This bug was found in**

- [x] Desktop
- [ ] Web App
- [ ] Both

**Describe the bug**
Trying to save a score to PDF now prints the page you are looking at only, as if you are taking a screenshot, with scroll bars visible too.

**To Reproduce**

1. File
2. Export as PDF
3. Save to directory of choice
4. See PDF

**Expected behavior**
Expected a 3 page PDF, for example, but got only the page I was on with scroll bars in the PDF

**Screenshots or files**
If applicable, add screenshots to help explain your problem. You may also upload a `byz` or `byzx` file, but you must first zip it and upload the `zip` file.
[test.pdf](https://github.com/neanes/neanes/files/15024526/test.pdf)
[Mary-Egypt-LIHC-Stichera-BN.zip](https://github.com/neanes/neanes/files/15024531/Mary-Egypt-LIHC-Stichera-BN.zip)

**Desktop Version (please complete the following information, if applicable):**
Windows App, version 0.4.23

**Additional context**
Seeing this issue only after the latest update

**Comment by Cityyankee24** [comment]
Forgot to add:
Windows App, version 0.4.23

**Comment by danielgarthur** [comment]
This has been fixed in [0.4.24](https://github.com/neanes/neanes/releases/tag/v0.4.24).
