### ISSUE TITLE
Rich text editor

### ISSUE THREAD

**Issue by panosmorningstar** [neanes/neanes#640]
Hi. 

Neanes is truly remarkable, very easy to use with a clean UI.

I propose to the developers the creation of different kinds of text boxes. This will result in the enrichment of the document with plain lyrics, creating whole ἀκολουθίαι. This could also include specific settings for the footnote/header text boxes.

Thank you.

**Comment by danielgarthur** [comment]
@panosmorningstar Would you please upload some pictures or PDFs that illustrate the kind of text you would like to see supported?

**Comment by panosmorningstar** [comment]
@danielgarthur 
[Uploading 2024-04-28_kyriakh_baiwn_e_(scores).pdf…]()

**Comment by danielgarthur** [comment]
The upload did not seem to work. Could you please try again?

**Comment by danielgarthur** [comment]
Never mind, I was able to find the PDF on the internet.

[2024-04-28_kyriakh_baiwn_e_(scores).pdf](https://github.com/neanes/neanes/files/15049251/2024-04-28_kyriakh_baiwn_e_.scores.pdf)

**Comment by danielgarthur** [comment]
Based on the file, it seems like the main thing is that Neanes does not currently rich text boxes that allow different font colors and styles in the same box. 

This is something that I've looked into several times in the past and the conclusion that I've come to every time is that it would be best to write my own rich text box, as opposed to trying to use an existing library.

I've put this off for a while to focus on other more essential features, but it may be time for me to look into rich text boxes again.

**Comment by basil** [comment]
Over a decade ago I enjoyed using [TinyMCE](https://github.com/tinymce/tinymce), but I have no idea if it is still relevant these days.

**Comment by danielgarthur** [comment]
Added to release [0.4.32](https://github.com/neanes/neanes/releases/tag/v0.4.32).

There is an example file in the examples folder [here](https://github.com/neanes/neanes/blob/master/examples/Rich%20Text.byzx) and a PDF of the example [here](https://github.com/neanes/neanes/blob/master/examples/Rich%20Text.pdf).

**Comment by danielgarthur** [comment]
Re-opening because the original request also includes rich text support in headers and footers. This is not completed yet, but I think it's worth including.

**Comment by danielgarthur** [comment]
Headers and footers have been added to [v0.4.34](https://github.com/neanes/neanes/releases/tag/v0.4.34).
