### ISSUE TITLE
Martyriae Pa and Ni of Ypate

### ISSUE THREAD

**Issue by panosmorningstar** [neanes/neanes#641]
Hi.

I'm currently transcribing a composition by Chourmouzios and certain rare types of martyriae are required. Namely, the ones of Ni and Pa of Ypate.

It would be great if these two could be added to the software.

Thank you!

**Comment by basil** [comment]
Fixed in https://github.com/neanes/neanes/pull/658. Released in [0.4.26](https://github.com/neanes/neanes/releases/tag/v0.4.26).
