### ISSUE TITLE
Alignment of pelastikon and gorthmikon

### ISSUE THREAD

**Issue by panosmorningstar** [neanes/neanes#665]
**This bug was found in**

- [x] Desktop
- [ ] Web App
- [ ] Both

After 4.25 update I noticed a problem in the alignment of pelastikon and gorthmikon. I provide an example featuring both of them.

Before the update:
![pelastikon 2](https://github.com/neanes/neanes/assets/167481301/847ca332-34f6-4df9-b67e-9f4586bb3d53)

After the update: 
![note indicator](https://github.com/neanes/neanes/assets/167481301/59628d31-802d-4fa0-a655-a29c98cf52a5)

**Comment by basil** [comment]
Bisected to #642
