### ISSUE TITLE
Spathi on Ni

### ISSUE THREAD

**Issue by panosmorningstar** [neanes/neanes#671]
There is a case in the following book by Kosmas Maditinos, where a spathi is place on Ni.

The book:

https://docviewer.yandex.ru/view/1965899164/?page=2&*=D5aoy9ISibK6%2F2oC6%2FT1zxiYlGl7InVybCI6InlhLWRpc2stcHVibGljOi8vWlNTZHljRWkzTGpPRUVxRWgrSStvdHh4U3loQ25VeUZkSWIrRzQzZ05iND06L86azp%2FOo86czpEgzpzOkc6UzqXOpM6Zzp3On86lLc6gzp%2FOmc6czpXOnc6ZzprOn86jIM6RzqXOm86fzqMtz4QuzpInLc6fzqHOmM6hzp%2FOoy3Om86VzpnOpM6fzqXOoc6TzpnOkSAoMTg5NykucGRmIiwidGl0bGUiOiLOms6fzqPOnM6RIM6czpHOlM6lzqTOmc6dzp%2FOpS3OoM6fzpnOnM6Vzp3Omc6azp%2FOoyDOkc6lzpvOn86jLc%2BELs6SJy3On86hzpjOoc6fzqMtzpvOlc6ZzqTOn86lzqHOk86ZzpEgKDE4OTcpLnBkZiIsIm5vaWZyYW1lIjpmYWxzZSwidWlkIjoiMTk2NTg5OTE2NCIsInRzIjoxNzE0MzQyOTIzODE4LCJ5dSI6IjczODI0NTc2ODE2OTU0ODc2MzkifQ%3D%3D

The except: 

![spathi Ni](https://github.com/neanes/neanes/assets/167481301/23307098-d93a-44ff-b72f-36f0da141b9c)

It would be nice if this option could be added to the software.

Thanks.

**Comment by danielgarthur** [comment]
Sorry, I missed this until just now.

This is already possible. In Page Setup, check the checkbox `Disable Fthora Restrictions`
<img width="308" alt="image" src="https://github.com/neanes/neanes/assets/4132779/a97a7913-3d93-41cd-86f9-bf31fa22d953">

You will have to manually override the martyria to get it to look like your example. 

Click on the martyria, and in the toolbar
1. Uncheck `Auto`.
2. Change the `Root Sign Override` to `Neanes`.

<img width="454" alt="image" src="https://github.com/neanes/neanes/assets/4132779/b7d452de-0307-4798-9801-40ed3502c394">
