### ISSUE TITLE
Melisma syllables should be aligned left under the first neume

### ISSUE THREAD

**Issue by basil** [neanes/neanes#696]
From Gardner Read, _Music Notation: A Manual of Modern Practice_ (Taplinger Publishing, New York, 1979):

![read](https://github.com/neanes/neanes/assets/29850/fbeef479-a508-4c06-a27c-9d55630b0eff)

From Elaine Gould, _Behind Bars: The Definitive Guide to Music Notation_ (Faber Music Ltd., London, 2011):

![gould1](https://github.com/neanes/neanes/assets/29850/46559a98-a5c0-4a56-8797-459572a04f7c)

![gould2](https://github.com/neanes/neanes/assets/29850/63493a93-7f7b-4194-96dd-c0452306367b)

**Comment by danielgarthur** [comment]
Do you have a mockup of what you imagine this looking like? Even something hand-drawn is fine. 

With music notes, the center of the note can be aligned with the center of the first letter of the word. I'm not sure how that translates to an ison or a petaste, for example.

**Comment by basil** [comment]
Sure, I should have elaborated further. In Western notation the lyric syllable is never smaller than the notehead, but in Byzantine notation the lyric syllable can be bigger or smaller than the neume.

If the lyric syllable is smaller than the neume, I think it should always be centered under the neume. This is standard practice and I don't see any reason to change it.

But if the lyric syllable is larger than the neume, as is always the case in Western notation, then the melisma should be left-aligned with the neume, as shown in the examples at the bottom of page 439 of _Behind Bars_. That is, the software currently produces

![before](https://github.com/neanes/neanes/assets/29850/d0f070b3-a6bc-475d-b4e9-e1e1468c12d0)

(which is analogous to the bad example to the right in _Behind Bars_)

while it should produce

![after](https://github.com/neanes/neanes/assets/29850/5e58244a-4c20-4a16-8a71-66d0e576c12c)

(which is analogous to the good example to the left in _Behind Bars_).

The reasoning, as described by Elaine Gould, is

> to draw the eye to the right—an important consideration, since the singer always needs to be looking forward.

Gardner Read makes the same point by writing "the first letter is usually aligned with the first note," but, in his characteristically terse style, does not explain the reasoning behind it. Gould acknowledges that "some editions place all syllables consistently to the left of the note, but, in general, this is not helpful." As with many of the finer points of typography, there is not always consensus among all editions, but there is consensus among the highest-quality editions.

One can see a pretty egregious example of this bug in https://github.com/basil/byzantine-music/blob/485268d11cca0e5a65377254782680d78313b58a/Eortologion%20-%20Doxastarion/Triodion/Joy%20of%20all%20that%20sorrow.byzx:

![before2](https://github.com/neanes/neanes/assets/29850/25da984f-f6fb-4213-8247-ae354d8cce1d)

Quite the opposite of Gould's point about drawing the eye to the right, here the lyric syllable draws the eye back to the left toward the previous neume, which is the opposite of what the singer needs to be doing. The fact that any part of "brought" appears underneath the preceding neume not only looks bad, but could be a source of confusion to the singer who might think the syllable belongs to that preceding neume. Here is a sketch of how I think it should look:

![sketch](https://github.com/neanes/neanes/assets/29850/07f192c2-f6f2-49fe-bbc5-7598f829d2b1)

**Comment by basil** [comment]
As usual, LilyPond gets this right, as you can see from the first three bars of _Dido's Lament_ [here](https://lilypond.org/doc/v2.24/Documentation/learning/aligning-lyrics-to-a-melody), typeset exactly as Gardner Read and Elaine Gould recommend.

**Comment by danielgarthur** [comment]
@basil Please check out the branch [696-left-align-melisma](https://github.com/neanes/neanes/tree/696-left-align-melisma). I'm still spot-checking it against existing scores before I merge it. Below is a section from your score with the new alignment.

<img width="331" alt="image" src="https://github.com/neanes/neanes/assets/4132779/9031d1c2-d19f-46e1-b69b-6bef1212e4d9">

One thing to note is that I also removed the requirement that at least one underscore must always be present. If I hadn't, there would be a tiny little line at the end of `brought` that looks like it shouldn't be there.

**Comment by danielgarthur** [comment]
@ilizol This also improves the example from #512.
<img width="85" alt="image" src="https://github.com/neanes/neanes/assets/4132779/561939f8-d731-49cc-b77d-e95fb903b2f4">

**Comment by basil** [comment]
Wow, this is a nice improvement. I spot checked a few scores and haven't noticed any major problems. In that example you just posted, the word extender for "those" is extending a little too far past the end of the apostrophos—in my hand drawn version, the second dashed line shows where the word extension should end.

(In my "He brought forth" example above, you get pretty weird results when changing the word to "brouuuuuuuuuuuuuuuught", but I don't mean to torture you with unrealistic test cases, so feel free to ignore this part if it is hurting more than helping.)

**Comment by danielgarthur** [comment]
@basil I'm not sure whether the following case is correct? Should `stead` be centered or left aligned? Since it doesn't span multiple notes, the syllable itself is not a melisma, and perhaps it should be centered as before? Based on the staff notation examples above, I'm thinking it should be centered. Thoughts?

Before:
<img width="67" alt="image" src="https://github.com/neanes/neanes/assets/4132779/01f15339-49e5-48b0-8cd3-6584ea1134c2">

After:
<img width="62" alt="image" src="https://github.com/neanes/neanes/assets/4132779/2d53eeb7-645f-444a-92fd-bce8ccad62fc">

If instead, `stead` spans two notes, the result does seem correct, however.
<img width="59" alt="image" src="https://github.com/neanes/neanes/assets/4132779/a4a5363a-afd5-4bd5-959e-392ce7506c08">

**Comment by basil** [comment]
Agreed, this is not a melisma, so it falls under the "single note per syllable" category in Gould's book ("centre each syllable directly under its note") as in the "before" example you posted.

**Comment by danielgarthur** [comment]
@basil The extender length should be fixed now with the latest commit.

<img width="329" alt="image" src="https://github.com/neanes/neanes/assets/4132779/0b7cc235-eafe-42d0-9c0f-e87b9bdf4491">

The "brouuuuuuuuught" thing was a result of not fully updating all the math to use the new logic. That should be fixed now too. It will still look strange, but not nearly as strange as before.

**Comment by basil** [comment]
I went through all my scores with this change, and it is a dramatic improvement. Many subtle cases—particularly involving the apostrophos, kentemata, and yporroe—now look better.

I think this change is certainly good enough to land. When the syllable is longer than the entire melisma, as in the "brought" in "unto those brought down by pain", or in the "souls" in

![ending](https://github.com/neanes/neanes/assets/29850/a539d000-51f0-4395-a46f-401c8b2cf1b4)

things can wind up feeling a bit too cramped, requiring manual intervention to add extra space. Both Gardner Read and Elaine Gould allude to the fact that manual adjustment is always going to be necessary for aesthetically perfect results ("allowing always for variations and exceptions when space requirements so dictate" and "from time to time there may be an aesthetic case for doing so"), but this change goes a long way to making the default output better in the vast majority of cases.

**Comment by danielgarthur** [comment]
Included in [0.4.31](https://github.com/neanes/neanes/releases/tag/v0.4.31)
