### ISSUE TITLE
Add line numbers

### ISSUE THREAD

**Issue by dliousas** [neanes/neanes#733]
It would be useful to be able to add line numbers into scores.

Here is an example from St. Anthony's Monastery DMP:
![image](https://github.com/neanes/neanes/assets/71402432/76cb166f-73b1-444b-ae88-79a3cdd1613c)

**Comment by danielgarthur** [comment]
A new feature has been added to [0.4.36](https://github.com/neanes/neanes/releases/tag/v0.4.36) that makes this easier.

If you click on a drop cap, you can set the `Width` in the bottom toolbar. 

<img width="733" alt="image" src="https://github.com/neanes/neanes/assets/4132779/29f0ba4e-94d6-49b8-a44e-2d6004261633">

If you want to adjust the vertical position of the drop cap, you can adjust the line height. That's the text box with the word `normal` in it, which is the default value. Try changing it to `0`, for example, and then increase it slowly to see how it works.

Setting each drop cap to the same width will provide consistent spacing between the line number and the neumes.

<img width="229" alt="image" src="https://github.com/neanes/neanes/assets/4132779/50cf9427-d681-48a1-a59e-08081229e90c">
