### ISSUE TITLE
Greek melisma syllable with upper case letters

### ISSUE THREAD

**Issue by ilizol** [neanes/neanes#745]
**Describe the bug**
Opening an old score with the latest version (`0.4.37`) and using the Greek melisma feature, syllable with upper case letters is repeated.

**Expected behavior**
Greek melisma syllable with upper case letters should be converted to lower case letters.

**Screenshot**
![capital_greek_melisma](https://github.com/neanes/neanes/assets/7188298/c5af99ea-2fa4-4537-8622-76397029f8a1)

**The source of testing score**
https://github.com/ilizol/neanes-examples/blob/main/kontakion_saint_basil_great/kontakion_saint_basil_great.byzx

**Expected result like the old PDF file**
https://github.com/ilizol/neanes-examples/blob/main/kontakion_saint_basil_great/kontakion_saint_basil_great.pdf

**Comment by danielgarthur** [comment]
Fix in [0.4.38](https://github.com/neanes/neanes/releases/tag/v0.4.38).
