### ISSUE TITLE
The distance (neumes-lyrics) becomes narrow in PDF

### ISSUE THREAD

**Issue by Eliekhacho** [neanes/neanes#764]
**This bug was found in**

- [x] Desktop
- [ ] Web App
- [ ] Both

**Describe the bug**

**To Reproduce**

**Expected behavior**
When I finished my Pentecost service ((Several pages). When I exported the file as PDF, I found the distance (neumes - lyrics) at the beginning of the next page became narrow.
And as HTML. text was aligned left instead of right.
 Are there any suggestions? Thank you. 

**Screenshots or files**
If applicable, add screenshots to help explain your problem. You may also upload a `byz` or `byzx` file, but you must first zip it and upload the `zip` file.
![image](https://github.com/neanes/neanes/assets/144347443/0028909c-d21c-43d2-8f74-e053edbf4086)

![image](https://github.com/neanes/neanes/assets/144347443/45e5dc47-b9ce-40f5-a5f3-3d6a7352b0ca)

**Desktop Version (please complete the following information, if applicable):**

- OS: Windows 10
- Version:0.4.39

**Web App (please complete the following information, if applicable):**
Note: That the web app version currently only supports Chromium-based browsers. Mobile devices are not currently supported. Please do not file a bug if not using an unsupported browser or a mobile device.

- Browser: Chrome
- Version: 126.0.6478.61

**Additional context**

**Comment by danielgarthur** [comment]
Possibly related to #71. I can reproduce this with A4 page size, but not Letter.

**Comment by danielgarthur** [comment]
Well, I _thought_ I was able to reproduce it, but now I can't. Could you please zip the byz file up and attach it?

**Comment by danielgarthur** [comment]
Please try [0.4.40](https://github.com/neanes/neanes/releases/tag/v0.4.40). This fixes the RTL issue when exporting rich text boxes to HTML.

I also found and fixed an issue with the neumes drifting higher toward the top of the page as the page count increased. However, I could not reproduce the issue with the lyrics drifting close to the neumes.

If you still see this issue in 0.4.40, please put the `.byz` file into a `.zip` archive and attach it to the comment.
