### ISSUE TITLE
Page Numbers and Title Pages

### ISSUE THREAD

**Issue by PeTH2** [neanes/neanes#781]
Presently page numbers can be added with the `$p` flag in headers and footers. Presently it only auto-assigns the numbers from the beginning of the document. Would it be possible to add the ability to set a different first page to have an unnumbered Title Page with no headers and footers.

**Comment by danielgarthur** [comment]
Both of these are currently possible. In the Page Setup dialog you can specify the first page number and specify that the first page should use a different header.

**Comment by PeTH2** [comment]
My apologies. I now see that. Thank you!
