### ISSUE TITLE
Playback of Ke in Third Mode. 

### ISSUE THREAD

**Issue by PeTH2** [neanes/neanes#821]
Linux, version 0.4.46.

In certain theseis that end on Ke, especially when Ke is followed by Zo, Ke plays back as flat Zo.

Here's a screen recording:

https://github.com/neanes/neanes/assets/128826899/dbcb8ccf-741e-4689-9160-096678729f46

**Comment by danielgarthur** [comment]
Related to #213. Unfortunately the Ke attraction rules described in that issue are also too simplistic. I'm going to disable Ke attraction for now until a more complete algorithm can be determined.

**Comment by PeTH2** [comment]
Thank you!

**Comment by danielgarthur** [comment]
Fixed in [0.4.47](https://github.com/neanes/neanes/releases/tag/v0.4.47). 

#606 should still be working, despite the partial rollback of the zo attraction feature.
