### ISSUE TITLE
Melisma spacing too tight

### ISSUE THREAD

**Issue by basil** [neanes/neanes#862]
In https://github.com/basil/byzantine-music/blob/1c7680a54a9c93c8c91ff557f5d6e1d27a59aff3/Mysteries%20and%20Sacraments/Paraklesis/18%20Ode%20Seven%20-%20Small.byzx the melisma spacing is too tight here:

![spacing](https://github.com/user-attachments/assets/6e371119-f8f0-4e8a-b47d-cbc3a19c2f7d)

While this has been tolerable in some other cases, in this case I think it has a negative effect on readability. I don't think a lyric syllable should ever extend beneath a preceding melisma neume, as "womb" does in this example. I suppose the expected behavior would be for an lyric extender (underscore) to be drawn for the "Maid's" melisma, with some extra whitespace added to the left of the apostrophos for "womb" (just as it already is to the right of the apostrophos).

**Comment by danielgarthur** [comment]
I agree that doesn't look good. I'm not sure how to balance between that and the example [here](https://github.com/neanes/neanes/issues/45#issuecomment-1379931129). 
![image](https://user-images.githubusercontent.com/116736628/212006401-c9963f9e-31df-48f1-bf62-e5e3e017b2f6.jpg).

Words are currently allowed to take up some melisma space to avoid the large gap between neumes in the above picture, but this has lead to other readability problems like in your example. How would you expect this example from the Praises to be rendered?

**Comment by basil** [comment]
https://github.com/basil/byzantine-music/blob/f65dcd7b7d2495e935c9471a23201df393b9b0eb/Anastasimatarion/Plagal%20of%20First%20Mode/Let%20every%20breath.byzx is typeset as expected …

![Let every breath-1](https://github.com/user-attachments/assets/27a5f381-5069-4f54-be09-235890da656d)

… which matches the behavior in LilyPond …

![lilypond](https://github.com/user-attachments/assets/f0520939-f1d3-4cfe-98e7-849c7984c6e4)

… and the advice in _Behind Bars_ for lyrics of a single note per syllable:

> If necessary the text may precede the barline.

I have found a workaround in https://github.com/basil/byzantine-music/commit/74b0f1adb669da71e287c28a43ebf57213e3e503 so I am closing this ticket.

**Comment by danielgarthur** [comment]
@basil I'd like to fix this either with https://github.com/neanes/neanes/pull/2209 or as a follow up PR. Especially since zero-spacing is going to exacerbate the issue.

**Comment by danielgarthur** [comment]
<img width="190" height="77" alt="Image" src="https://github.com/user-attachments/assets/f8dd93ce-7a17-40a7-9c6a-99ed16f625a5" />

Acceptable? 

Before, the entire melisma would vanish.

<img width="115" height="74" alt="Image" src="https://github.com/user-attachments/assets/f852ee15-1eff-45a4-810d-f96af7e04ed4" />

**Comment by basil** [comment]
Yeah, that is definitely a big improvement. Another improvement that I had in the back of my mind (but didn't want to burden you with in my last comment) was to center-align (rather than left-align) melismas whose opening syllable is longer than the melisma itself. E.g. to center align this:

<img width="810" height="242" alt="Image" src="https://github.com/user-attachments/assets/3e8fe2d5-dacf-490f-95df-14b0c9874840" />

(Current behavior is to left-align it, like all melismas.)

However I didn't know how hard that would be, and certainly not a blocking request.
